name: restful-web-services
services:
  postgresql:
    container_name: postgresql-docker-restful-web-services-database
    image: postgres:15.0-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restful-web-services
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql